### ISSUE TITLE
Blog engine

### ISSUE THREAD

**Issue by doomspork** [elixirschool/appendix#1]
Jekyll, Ghost, Medium, or what?

RFC @elixirschool/developers

**Comment by ybur-yug** [comment]
I vote against medium. Incredibly heavy page sizes that alienate a lot of our core audience because we have so many translations but there are a _lot_ of places w/o connection speeds that will load a medium page like they would the current main elixir school site.

Ghost is simple and I liked it in the small experience I had.

Jekyll is already giving us limitations on your vision for the bigger picture on the main site, if were trying to think ahead I think that it might just repeat history assuming this project continues to grow (which we obviously intend).

Maybe we could build some content for elixir school itself that builds up the blog engine (or a slightly simplified version thereof) that actually runs the main site. Dogfooding is good.

**Comment by doomspork** [comment]
I'm leaning towards Jekyll because we've got "in-house" experience with it and the limitations we faced with the main site were features the blog won't include (PDF generation and interactivity).

Another advantage is we could consider using GitHub Pages.

Going to leave this for a bit longer to give other folks a chance to chime in.

**Comment by doomspork** [comment]
Jekyll it will be 👍
